[editor]
title = "Grackle Level Editor"

[viewport]
free = "Freie Kamera"
front = "Vorne"
top = "Oben"
right = "Rechts"
ui = "UI-Kamera"

[debug.viewport]
title = "Multicam-Ansicht"
controls = "Steuerelemente komprimieren"
start = "Start"
end = "Ende"

[debug.viewport.draw]
title = "Debug-Indikatoren zeichnen"
mouse = "Mauskreis"
box = "Ansichtsrahmen"
mouseover = "Mouseover-Rahmen"
probe = "Maus-Sonde"

[debug.movement]
title = "Kamerabewegung"
perspective.title = "Perspektivkamera-Einstellungen"
perspective.pan = "Perspektivkamera-Schwenkfaktor"
perspective.rotate = "Perspektivkamera-Rotationsfaktor"
perspective.speed = "Perspektivkamera-Geschwindigkeit"
perspective.scroll = "Perspektivkamera-Scroll-Geschwindigkeit"
orthographic.title = "Orthografische Kamera-Einstellungen"
orthographic.scroll = "Orthografische Kamera-Scroll-Geschwindigkeit"

[tools]
title = "Werkzeuge"
select = "Auswählen"
point = "Punkt"
point_light = "Punktlicht"
move = "Bewegen"
room = "Raum"

[bakes]
title = "Bake-Vorgänge"
room_geometry = "Raumgeometrie"

[show]
title = "Ein-/Ausblenden"
cameras = "Kameras"
ortho_cameras = "Orthografische Kameras"
perspective_cameras = "Perspektivkameras"
gizmos_title = "Gizmos"
gizmos_points = "Punkte"
gizmos_rooms = "Räume"
gizmos_point_lights = "Punktlichter"

[room.messages]
ghost = "Raum { me } ist vollständig in { other } enthalten und wird nicht angezeigt!"

[room.confirm]
title = "Raum-Ersteller"
confirm = "Bestätigen"

[debug.room]
title = "Raum-Werkzeug Debug"
state = "Aktueller Werkzeugzustand"
last_min = "Letztes Min: { x }"
last_max = "Letztes Max: { x }"
active_min = "Aktives Min: { x }"
active_max = "Aktives Max: { x }"
show_points = "Punkte anzeigen"
show_cursor = "Cursor in Weltkoordinaten anzeigen"
invalid_cursor = "Cursor befindet sich in einem ungültigen Zustand!"
missing_material = "Raum-Werkzeug ist in einen ungültigen Zustand geraten – Handles fehlen Materialien!"
gizmos = "Gizmos"

[debug.room.snap]
title = "Einrasten"
granularity = "Granularität"
active = "Am Raster einrasten"

[editor.timeline]
title = "Zeitleiste"
undo = "Rückgängig"
redo = "Wiederherstellen"
delete = "Löschen"

[editor.history]
title = "Verlauf"
undo = "Rückgängig"
redo = "Wiederholen"
empty = "Noch keine Aktionen."

[editor.metadata]
title = "Metadaten"
schema_version = "Schemaversion"
game_mode = "Spielmodus"
authors = "Autoren"

[editor.features.global_point]
title = "Globaler Punkt"

[editor.features.room]
title = "Raum"

[editor.features.grackle_point_light]
title = "Punktlicht"
params = "Lichtparameter"
intensity = "Intensität"
radius = "Radius"
range = "Reichweite"

[editor.features.cuboid]
title = "Quader"
