[editor]
title = "Grackle Level Editor"
title_special = "{ game } Grackle Level Editor"

[viewport]
free = "Freecam"
front = "Front"
top = "Top"
right = "Right"
ui = "UI Camera"

[debug.viewport]
title = "Multicam Viewport"
controls = "Squish Controls"
start = "Start"
end = "End"

[debug.viewport.draw]
title = "Draw Debug Indicators"
mouse = "Mouse Circle"
box = "Viewport Box"
mouseover = "Mouseover Boxes"
probe = "Mouse Probe"

[debug.movement]
title = "Camera Movement"
perspective.title = "Perspective Camera Settings"
perspective.pan = "Perspective camera pan factor"
perspective.rotate = "Perspective camera rotate factor"
perspective.speed = "Perspective camera speed"
perspective.scroll = "Perspectiva camera scroll speed"
orthographic.title = "Orthographic Camera Settings"
orthographic.scroll = "Orthographic camera scroll speed"

[tools]
title = "Tools"
select = "Select"
point = "Point"
point_light = "Point Light"
move = "Move"
room = "Room"

[bakes]
title = "Bake Operations"
room_geometry = "Room Geometry"

[show]
title = "Show/Hide"
cameras = "Cameras"
ortho_cameras = "Orthographic Cameras"
perspective_cameras = "Perspective Cameras"
gizmos = "Gizmos"

[show.gizmos]
points = "Points"
rooms = "Rooms"
point_lights = "Point Lights"

[room.messages]
ghost = "Room { me } is fully inside { other } and will not appear!"

[room.confirm]
title = "Room Creator"
confirm = "Confirm"

[debug.room]
title = "Room Tool Debug"
state = "Current Tool State"
last_min = "Last min: { x }"
last_max = "Last max: { x }"
active_min = "Active min: { x }"
active_max = "Active max: { x }"
show_points = "Show points"
show_cursor = "Show camera worldspace cursor"
invalid_cursor = "Cursor is in an invalid state!"
missing_material = "Room tool got in an invalid state with handles missing materials!"
gizmos = "Gizmos"

[debug.room.snap]
title = "Snap"
granularity = "Granularity"
active = "Snap to grid"

[editor.timeline]
title = "Timeline"
undo = "Undo"
redo = "Redo"

[editor.actions.global_point]
title = "Global Point"

[editor.actions.room]
title = "Room"

[editor.actions.grackle_point_light]
title = "Point Light"
params = "Light Parameters"
intensity = "Intensity"
radius = "Radius"
range = "Range"

[editor.actions.cuboid]
title = "Cuboid"

[crate_drop]
title = "Grackle Crate Tester"

[crate_drop.error]
no_odds = "A crate series entry for `{ item }` cannot be plain but it has no quality entries!"
quality_loop = "A crate unlock for `{ item }` got stuck in a loop while determining qualities!"
no_such_series = "A crate unlock was tried on a crate with series `{ series }` but no such series exists!"
no_such_prototype = "During a crate unlock, the selected entry wanted to crate a `{ prototype }`, but no such prototype exists."
invalid_entry_choice = "The crate drop RNG generated the number `{ entry }` which does not exist in the series."

[crate_drop.controls]
title = "Crate Drop"
new = "New Drop"
series = "Series"
select = "Select"

[crate_drop.details]
title = "Item Details"
none = "No item selected."

[crate_drop.history]
title = "Items"

[item]
stat_tracker_adj = "Strange"
stat_tracker_info = "Item tracks statistics about this item's use in matches."
stat_tracker = "Strange { item }"
particle_effect_adj = "Unusual"
particle_effect_info = "Item has a special particle effect."
particle_effect = "Unusual { item }"
trade_restriction = "Not tradeable."
crafting_restriction = "Not craftable."

[item.name]
shotgun = "Shotgun"
medigun = "Medigun"
top_hat = "Honest Abe"

[particle_effect]
electric = "Sparky"
fire = "Stop, Drop, n' Roll"
fire-blue = "Industrial Fire"

[stat_tracker]
tracks = "Tracks: { list }"
kills = "Frags"
assists = "Kill Assists"
damage = "Damage Dealt"
points = "Points Scored"
healing = "Healing"
